// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbzssHNL7pnyOXuoFhKkjYsplwsiJCuS4',
    appId: '1:348509094816:web:2e2ffd2ccf5778ddcb5ac5',
    messagingSenderId: '348509094816',
    projectId: 'surveyist-b7fa6',
    authDomain: 'surveyist-b7fa6.firebaseapp.com',
    storageBucket: 'surveyist-b7fa6.firebasestorage.app',
    measurementId: 'G-KN3G2ZHT1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ12jtRcr1829H2RhpK5bHiUOPFSOc4EI',
    appId: '1:348509094816:android:a54460463b0ace5acb5ac5',
    messagingSenderId: '348509094816',
    projectId: 'surveyist-b7fa6',
    storageBucket: 'surveyist-b7fa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH05SSmOeKSAulWyiqwQZTUSOhlsCvewc',
    appId: '1:348509094816:ios:33176fc0e08188aecb5ac5',
    messagingSenderId: '348509094816',
    projectId: 'surveyist-b7fa6',
    storageBucket: 'surveyist-b7fa6.firebasestorage.app',
    iosBundleId: 'com.example.surveyist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH05SSmOeKSAulWyiqwQZTUSOhlsCvewc',
    appId: '1:348509094816:ios:33176fc0e08188aecb5ac5',
    messagingSenderId: '348509094816',
    projectId: 'surveyist-b7fa6',
    storageBucket: 'surveyist-b7fa6.firebasestorage.app',
    iosBundleId: 'com.example.surveyist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbzssHNL7pnyOXuoFhKkjYsplwsiJCuS4',
    appId: '1:348509094816:web:572194e5e3cc6f3dcb5ac5',
    messagingSenderId: '348509094816',
    projectId: 'surveyist-b7fa6',
    authDomain: 'surveyist-b7fa6.firebaseapp.com',
    storageBucket: 'surveyist-b7fa6.firebasestorage.app',
    measurementId: 'G-Z8KZ0QJ37W',
  );
}
